name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
      - dev

jobs:
  unit_tests:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Unit Tests
        run: ./gradlew unitTest

  integration_tests:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        env:
          SQL_DB_URL: ${{ secrets.SQL_DB_URL }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: ./gradlew test

  build_push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: unit_tests
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build without running tests
        run: ./gradlew build -x unitTest -x test

  build_pull:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: integration_tests
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build without running tests
        run: ./gradlew build -x unitTest -x test

  docker_publish:
    needs: build_push
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Verify JAR file exists
        run: |
          if [ ! -f build/libs/finance_tracker-0.0.1-SNAPSHOT.jar ]; then
            echo "JAR file not found!"
            exit 1
          fi

      - name: Build Docker image
        run: docker build -t finance-tracker:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker tag finance-tracker:latest your-dockerhub-username/your-docker-image-name:latest
          docker push your-dockerhub-username/your-docker-image-name:latest
