name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main  # Trigger on PRs targeting main

jobs:
  unit_tests:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Unit Tests
        run: ./gradlew clean unitTest

  integration_tests:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run Docker Compose
        run: |
          docker-compose up -d 
          sleep 30

      - name: Build with Gradle
        env:
          SPRING_PROFILE: test
        run: ./gradlew clean test

      - name: Tear Down Docker Compose
        run: docker-compose down

  fast_forward_dev:
    if: github.event_name == 'pull_request' && github.head_ref == 'dev' && github.base_ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Fetch and Fast-forward dev branch
        run: |
          git fetch origin dev
          git checkout dev
          git merge --ff-only main
          git push origin dev || echo "Failed to push to dev branch"

  docker_publish:
    if: github.event_name == 'pull_request' && github.head_ref == 'dev' && github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t finance-tracker:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker tag finance-tracker:latest ${{ secrets.DOCKER_USERNAME }}/finance-tracker:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/finance-tracker:latest
